version: '3'
services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sreality_db
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python app.py'
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - scraper
  scraper:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; cd sreality_scrapy;  scrapy crawl sreality'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/sreality_db
volumes:
  postgres-data: